language: python
os: linux
python:
- '3.6.1'
- '3.7'
- '3.8'
before_install:
- pip install poetry
install:
- poetry install
- poetry install -E opencv
script:
- poetry run pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: A2G0h+phTKacGNxKpSUPpMHCG315fxhnW24nXY/bw7/sKdo3tAvr5PaCF6sJYI4K/MgEeJmAeVY0Ax/A7GSNEMigUmGVwGwE46U92QSQvnxPM8x7nLN8YypsLib0suXOKvmQSlzEiAI5/fok/Cvi6IeJFA/fhJFGmL+qPSwtN/91954Scvl+zLQU9/59HI1RfTL1U/pn6N9ve1fjax128lc56S1kXy1Rdqk8crVd+6yxI1SbbauGTb+0OUgKxlfRuaSINnWyilqAuFyqPPVqEfUWcSHkb58i9ToSkJwZc4YAhFL16hHw8tnOnlVfhbb13FmLxAty5G0tWZQs+KPaxM+ogkB9joiGixmVZX8It4zGqhgJejPNvrmJYWjX2+1m6KxUG2yKOA5K7Fa/F7tOshrBAxgtlwLyhQ+b4QNcPyQT4XE/iJuHgYRlh1ScnBa7KbOF7jalYFKNaFepuisFnVWdYvvnnCvTZ50NOSNBMa+2RBbHWo3CkW1YsnxOP17A16WqTcxRyNctkEIUya094/5cMHNEv2BVqLemjxnx6y0IFOCy4aqbSiMgTU4Veeuc/hz2Pu+J/4tgs17xV/3PPnfsWHHlemWnZwiyjSZT333G6ymDsPNmzW20uijJ+LLZ0aRZSC1JasOgSG1u3uBs43cl9p13PQ0i+zGzdHjGWfw=
