language: python
os: linux

python:
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
  - pip install poetry

install:
  - poetry install
  - poetry install -E opencv

script:
  - poetry run pytest
