language: python
os: linux
python:
- '3.6.1'
- '3.7'
- '3.8'
before_install:
- pip install poetry
install:
- poetry install
- poetry install -E opencv
script:
- poetry run pytest
deploy:
  provider: script
  script: poetry publish --build -u __token__ -p $PYPI_API_KEY
