[tool.poetry]
name = "BiKiPy"
version = "0.0.1"
license = "GPL-3.0-or-later"
description = "Liberary for automatic analysis of kinematic data"
authors = ["Can H. Tartanoglu <canhtart@gmail.com>"]

readme = "README.md"
packages = [{include = "bikipy"}]

[tool.poetry.dependencies]
python = ">=3.11.0,<3.12"
pydantic = "^2.0"
click = "^8.1.3"

# Owned by author
project-kit = {path = "../project-kit", develop=true}
pydantic-numpy = "*"

rtoml = "^0.9.0"

moviepy = "^1.0.3"
inflection = "^0.5.1"
psutil = "^5.9.4"
typing-inspect = "^0.8.0"

numpy = "*"
numba = { version = "*", allow-prereleases = true }
scipy = "^1.8.0"
scikit-learn = "^1.1.2"
statsmodels = "^0.13.1"
scikit-guess = {git = "https://gitlab.com/madphysicist/scikit-guess"}

pandas = { version = "^2.0.0", extras = ["performance", "compression", "hdf5", "parquet", "excel"] }

parsimonious = "^0.10.0"

matplotlib = "^3.2.2"
seaborn = "*"
mplcairo = {git = "https://github.com/matplotlib/mplcairo"}

ffmpeg-python = "^0.2.0"
opencv-python-headless = "^4.5"

tqdm = "*"
yaspin = "*"

compress-pickle = {extras = ["lz4"], version = "*"}
pydantic-settings = "^2.0.3"

[tool.poetry.group.dev.dependencies]
mypy = "*"
pytest = "^7.1.2"
snakeviz = "*"
mextractor = "*"    # owned by author

[tool.poetry.group.doc.dependencies]
Sphinx = "*"
sphinx-material = "*"
sphinx-autoapi = "*"

[tool.poetry.extras]
live = ["pyzmq"]
jupyter = ["jupyter", "jupyterthemes"]

[tool.poetry.scripts]
bkpy = "bikipy.cli:cli_root"



[tool.pytest.ini_options]
env = {"TESTING" = "1"}

[tool.mypy]
python_version = "3.11"
plugins = "numpy.typing.mypy_plugin"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
