[project]
name = "bikipy"
version = "0.0.1"
license = { text = "GPL-3.0-or-later" }
description = "Liberary for automatic analysis of kinematic data"
authors = [
    { name = "Can H. Tartanoglu", email = "canhtart@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "pydantic>=2.0",
    "pydantic-settings",
    "click>=8.1.3",
    "project-kit @ file:///data/can-data/Projects/project-kit",
    "pydantic-numpy",
    "mextractor>=4.0.1",
    "rtoml>=0.10.0",
    "moviepy>=1.0.3",
    "inflection>=0.5.1",
    "psutil>=5.9.4",
    "typing-inspect>=0.9.0",
    "numpy<2.0.0",
    "numba",
    "scipy>=1.8.0",
    "scikit-learn>=1.1.2",
    "statsmodels>=0.14.1",
    "pandas[performance,compression,hdf5,parquet,excel]>=2.0.0",
    "parsimonious>=0.10.0",
    "matplotlib>=3.2.2",
    "seaborn",
    "mplcairo @ git+https://github.com/matplotlib/mplcairo",
    "ffmpeg-python>=0.2.0",
    "opencv-python>=4.9",
    "tqdm",
    "yaspin",
    "compress-pickle[lz4]",
]

[project.scripts]
bkpy = "bikipy.cli:cli_root"

[dependency-groups]
dev = [
    "pytest>=8",
]
format = [
    "ruff",
]
type-checking = [
    "pyright",
]

[tool.ruff]
line-length = 120

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
