[immutable]
metadata_filename = "metadata.xlsx"
experiment_class = "rectangle"
trial_sequence = ["GenericRectangleEnclosedTrial"]

[developer]
activate_debugging = false

[developer.settings]
disable_numba = false
disable_process_pooling = false
only_physical_cores = false

[ingress]
method = "animal"
animal_profile = "rodent"
first_stage_is_habituation = true
metadata_trial_ids_are_higher_level = false
trial_sequence_loops = ""

dataset_directory = "/Users/can/Downloads/habituation_dataset"
profile_runtime = true

[definition_strategies]
meters_per_pixel = "metadata"
perimeter = ""
enclosure = ""
radial = ""
change_reference = ""
frame = "trial-wise"
video = ""
timestamp = ""
center = "metadata"

[manual_reader_kwargs]
[manual_reader_kwargs.defined]
object_tracking_label_for_kinematics = ""
cache_meters_augmented = false

[manual_reader_kwargs.required]
object_tracking_label_for_kinematics = "string"

[manual_reader_kwargs.optional]
cache_meters_augmented = "boolean -> True"
crop_from_end = "boolean -> False"
cropped_total_seconds = "number -> 0.0"
df_is_timestamped = "boolean -> False"
df_read_kwargs = "object"
export_timestamp_data_as_parquet = "boolean -> False"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
future_scaling = "boolean"
invert_y_axis = "boolean -> False"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
midpoint_groups = "object"
min_likelihood = "number -> 0.8"
minimum_frame_length = "integer -> 600"
model = "boolean -> True"
model_displacement_by_std = "number -> 2.0"
model_kwargs = "object"
model_method = "string -> arima"
manual_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"
required_tail_likelihood = "number -> 0.8"
x_axis_crop_end_point = "number -> 0.0"
y_axis_crop_end_point = "number -> 0.0"

[trial]
[trial.common]
[trial.common.defined]
manual_center_rectangle_dimensions_meters = [0.45, 0.45]

[trial.common.optional]
center_rectangle_dimensions_to_spatial_resolution_ratio = "number"
coordinate_timestamp_index = "np.ndarray"
crop_from_end = "boolean -> False"
cropped_total_seconds = "number -> 0.0"
enclosure = "[{'$ref': '#/definitions/BasePerimeter'}]"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
inspect_arg = "[{'type': 'string', 'format': 'path'}, {'type': 'boolean'}] -> False"
inspect_image_path = "string"
length_meters_of_meters_per_pixel_source = "number"
manual_center_pixels = "np.ndarray[name='manual_center_pixels_0' type=short required=True]"
manual_center_rectangle_dimensions_meters = "np.ndarray[name='manual_center_rectangle_dimensions_meters_0' type=dobble required=True]"
manual_enclosure = "[{'$ref': '#/definitions/BasePerimeter'}]"
manual_inspect_image = "np.ndarray[name='manual_inspect_image_0' type=uint8 required=True]"
manual_perimeter_to_derive_meters_per_pixel = "string"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
meters_per_pixel_from_perimeter = "boolean -> False"
meters_per_pixel_from_perimeter_source = "string"
minimum_frame_length = "integer -> 600"
reader_class_label = "string -> DeepLabCutReader"
manual_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"
rectangle_2d_bin = "array -> (2, 2)"
rigid_nodes_freezing = "array"
trial_start_perimeter = "string"

[trial.specific.GenericRectangleEnclosedTrial.defined]

[experiment]
[experiment.defined]
fps = 15

[experiment.optional]
compute_first_two_feature_series_only = "boolean -> False"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
inspect_arg = "[{'type': 'string', 'format': 'path'}, {'type': 'boolean'}] -> False"
inspect_image_path = "string"
manual_inspect_image = "np.ndarray[name='manual_inspect_image_0' type=uint8 required=True]"
manual_trial_ids = "array"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
minimum_frame_length = "integer -> 600"
manual_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"
skip_habituation = "boolean -> False"
stage = "string"
trial_init_error_out_dir = "string"
