[immutable]
metadata_filename = "metadata.xlsx"
experiment_class = "y_maze"
trial_sequence = ["YMazeTrial"]

[debug]
activate_debugging = false
no_numba = false
no_process_pooling = false

[ingress]
method = "phase"
first_stage_is_habituation = false
metadata_trial_ids_are_higher_level = false
trial_sequence_loops = 1
framewise_coordinates_file_suffix = ".parquet"
dataset_directory = "/mnt/soma/Projects/Neuroscience/Imen/data/y_maze/"
profile_runtime = true

[definition_strategies]
meters_per_pixel = ""
perimeter = ""
radial = ""
change_reference = ""
frame = ""
video = ""
timestamp = ""
center = ""

[manual_reader_kwargs]
[manual_reader_kwargs.defined]
x_axis_crop_end_point = 95.0
y_axis_crop_end_point = 75.0
invert_y_axis = true

[manual_reader_kwargs.defined.midpoint_groups]
center_eye = ["left_ear", "right_ear"]
torso = ["center_eye", "base_tail"]

[manual_reader_kwargs.optional]
cache_meters_augmented = "boolean -> True"
crop_from_end = "boolean -> False"
crop_time_seconds = "number -> 0.0"
df_is_timestamped = "boolean -> False"
df_read_kwargs = "object"
export_timestamp_data_as_parquet = "boolean -> False"
filter_displacement_by_std = "number -> 2.0"
filter_kwargs = "object"
filter_method = "string -> arima"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
future_scaling = "boolean"
invert_y_axis = "boolean -> False"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
midpoint_groups = "object"
min_likelihood = "number -> 0.8"
minimum_frame_length = "integer -> 600"
recording_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"
required_tail_likelihood = "number -> 0.8"
x_axis_crop_end_point = "number -> 0.0"
y_axis_crop_end_point = "number -> 0.0"

[trial]
[trial.common]
[trial.common.defined]
object_labels_for_y_maze_confinement_tracking = ["center_eye", "torso", "base_tail"]
object_tracking_label_for_kinematics = "torso"

[trial.common.required]
object_labels_for_y_maze_confinement_tracking = "array"
object_tracking_label_for_kinematics = "string"

[trial.common.optional]
coordinate_timestamp_index = "np.ndarray"
crop_from_end = "boolean -> True"
crop_time_seconds = "number -> 0.0"
enclosure = "[{'$ref': '#/definitions/BasePerimeter'}]"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
inspect_arg = "[{'type': 'string', 'format': 'path'}, {'type': 'boolean'}] -> False"
inspect_image_path = "string"
length_meters_of_meters_per_pixel_source = "number"
manual_center_pixels = "np.ndarray[name='manual_center_pixels_0' type=short required=True]"
manual_inspect_image = "np.ndarray[name='manual_inspect_image_0' type=uint8 required=True]"
manual_perimeter_to_derive_meters_per_pixel = "string"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
meters_per_pixel_from_perimeter = "boolean -> False"
meters_per_pixel_from_perimeter_source = "string"
minimum_frame_length = "integer -> 600"
minimum_seconds_for_entry = "number -> 0.5"
reader_class_label = "string -> DataWithLikelihoodReader"
recording_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"
rigid_nodes_freezing = "array"
trial_start_perimeter = "string"

[trial.specific.YMazeTrial.defined]

[experiment]
[experiment.defined]

[experiment.optional]
compute_first_two_feature_series_only = "boolean -> False"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
inspect_arg = "[{'type': 'string', 'format': 'path'}, {'type': 'boolean'}] -> False"
inspect_image_path = "string"
manual_inspect_image = "np.ndarray[name='manual_inspect_image_0' type=uint8 required=True]"
manual_trial_ids = "array"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
minimum_frame_length = "integer -> 600"
recording_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"
skip_habituation = "boolean -> False"
stage = "string"
trial_init_error_out_dir = "string"
