ingress:
  method: animal
  first_stage_is_habituation: false
  trial_sequence_repetitions: null
  framewise_coordinates_file_suffix: .parquet
  minimum_frame_length: 500
  dataset_directory: /home/can/Downloads/Compressed/rosy_nort/dataset/
  profile_runtime: true
  outdated:
    frame_upscale_multiplier: float
definition_strategies:
  meters_per_pixel: global
  perimeter: metadata
  radial: null
  change_reference: null
  frame: null
  video: trial-wise
  timestamp: null
  center: null
perimeter:
  label_prefix: null
  label_suffix: null
  perimeter_names_in_metadata: true
  radial_arm_rectangle_diagonal: null
  fields:
    defined: {}
    optional:
      category: string -> video_metadata
      derive_meters_per_pixel: boolean -> False
      derived_meters_per_pixel_source: string
      derived_meters_per_pixel_source_metric_length: number
      fps: number
      frame: '[{''type'': ''string'', ''format'': ''file-path''}, {''type'': ''uint8''}]'
      impenetrable: boolean -> False
      inspect_arg: '[{''type'': ''string'', ''format'': ''path''}, {''type'': ''boolean''}]
        -> False'
      inspect_image_path: string
      manual_inspect_image: np.ndarray
      manual_video: None
      meters_per_pixel: np.ndarray[name='meters_per_pixel_0' type=dobble required=True]
      minimum_frame_length: number
      moving_field_name: string
      recording_resolution: np.ndarray[name='recording_resolution_0' type=short required=True]
      outdated:
        image_resize_multiplier: number
        manual_fps: number
        manual_frame: '[{''type'': ''np.ndarray''}, {''type'': ''string'', ''format'':
          ''file-path''}]'
        manual_recording_resolution: np.ndarray[name='manual_recording_resolution_0'
          type=short required=True]
        video_path: string
reader_kwargs:
  defined:
    midpoint_groups:
      center_eye:
      - left_ear
      - right_ear
      torso:
      - center_eye
      - tail_base
  optional:
    cache_meters_augmented: boolean -> True
    category: string -> video_metadata
    crop_from_end: boolean -> False
    crop_time_seconds: number -> 0.0
    df_is_timestamped: boolean -> False
    df_read_kwargs: object
    export_timestamp_data_as_parquet: boolean -> False
    filter_data: boolean -> True
    filter_kwargs: object
    filter_method: string
    fps: number
    frame: '[{''type'': ''string'', ''format'': ''file-path''}, {''type'': ''uint8''}]'
    future_scaling: boolean
    ignore_likelihoods: boolean -> False
    invert_y_axis: boolean -> False
    manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
    meters_per_pixel: '[{''type'': ''number''}, {''type'': ''dobble''}]'
    midpoint_groups: object
    min_likelihood: number -> 0.8
    minimum_frame_length: number
    recording_resolution: np.ndarray[name='recording_resolution_0' type=short required=True]
    x_axis_crop_end_point: number -> 0.0
    y_axis_crop_end_point: number -> 0.0
trial:
  common:
    defined:
      gaze_start_point_label: center_eye
      gaze_travel_direction_point_label: nose
      meters_per_pixel_from_perimeter_source: null
      object_tracking_label_for_kinematics: torso
      perimeter_border_normal_meters: 0.03
      outside_perimeter_point_label: torso
      outdated:
        manual_frame: /home/can/Projects/bikipy/examples/sequence/NORT/inspect.png
        manual_fps: 30
      physical_object_inspect: true
      maximum_radians_inter_gaze_perimeter: 0.7853981633974483
    required:
      gaze_start_point_label: string
      gaze_travel_direction_point_label: string
      meters_per_pixel_from_perimeter_source: string
      object_tracking_label_for_kinematics: string
      perimeter_border_normal_meters: number
    optional:
      category: string -> video_metadata
      center_rectangle_dimensions_to_spatial_resolution_ratio: number
      coordinate_timestamp_set: np.ndarray
      crop_from_end: boolean -> True
      crop_time_seconds: number -> 0.0
      data_format_label: string -> deeplabcut
      fps: number
      frame: '[{''type'': ''string'', ''format'': ''file-path''}, {''type'': ''uint8''}]'
      inspect_arg: '[{''type'': ''string'', ''format'': ''path''}, {''type'': ''boolean''}]
        -> False'
      inspect_image_path: string
      length_meters_of_meters_per_pixel_source: number
      manual_center_pixels: np.ndarray[name='manual_center_pixels_0' type=short required=True]
      manual_center_rectangle_dimensions_meters: np.ndarray[name='manual_center_rectangle_dimensions_meters_0'
        type=dobble required=True]
      manual_inspect_image: np.ndarray[name='manual_inspect_image_0' type=uint8 required=True]
      manual_perimeter_to_derive_meters_per_pixel: string
      manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
      maximum_radians_inter_gaze_perimeter: number -> 0.7853981633974483
      maximum_seconds_distraction: number -> 0.6666666666666666
      meters_per_pixel: '[{''type'': ''number''}, {''type'': ''dobble''}]'
      meters_per_pixel_from_perimeter: boolean -> False
      minimum_frame_length: number
      minimum_seconds_attention: number -> 0.3333333333333333
      outside_perimeter_point_label: string
      physical_object_inspect: boolean -> False
      recording_resolution: np.ndarray[name='recording_resolution_0' type=short required=True]
      rectangle_2d_bin: array -> (2, 2)
      rigid_nodes_freezing: array
      trial_start_perimeter: string
  specific:
    NortTrainingTrial:
      defined: {}
    NortNoveltyTrial:
      defined: {}
experiment:
  defined: {}
  optional:
    category: string -> video_metadata
    compute_first_two_feature_series_only: boolean -> False
    data_format_label: string -> deeplabcut
    fps: number
    frame: '[{''type'': ''string'', ''format'': ''file-path''}, {''type'': ''uint8''}]'
    inspect_arg: '[{''type'': ''string'', ''format'': ''path''}, {''type'': ''boolean''}]
      -> False'
    inspect_image_path: string
    manual_inspect_image: np.ndarray[name='manual_inspect_image_0' type=uint8 required=True]
    manual_trial_ids: array
    manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
    meters_per_pixel: '[{''type'': ''number''}, {''type'': ''dobble''}]'
    minimum_frame_length: number
    recording_resolution: np.ndarray[name='recording_resolution_0' type=short required=True]
    skip_habituation: boolean -> False
    stage: string
    trial_init_error_out_dir: string
debug:
  activate_debugging: false
  no_numba: false
  no_process_pooling: false
immutable:
  metadata_filename: metadata.xlsx
  experiment_class: NortExperiment
  stage_index_to_trial_class_name:
    0: NortTrainingTrial
    1: NortNoveltyTrial
