[manual.jit_init]
ingress_method = "animal"
experiment_name = "oul"

[ingress]
required = ["dataset_directory", "definition_meters_per_pixel", "project_kit_config"]
optional = ["definition_center", "definition_change_reference", "definition_enclosure", "definition_frame", "definition_radial", "definition_single_perimeter", "definition_timestamp", "definition_video", "deprecated_project_settings_file_name", "first_stage_is_habituation", "ingress_defined_perimeters", "metadata_trial_ids_are_higher_level", "trial_sequence_loops"]

[ingress.defined]
dataset_directory = "/home/can/data/oul/OUL_combined_mextracted/"
definition_meters_per_pixel = ["metadata"]
definition_single_perimeter = ["trialwise"]
definition_enclosure = ["metadata"]
definition_center = ["metadata"]
definition_timestamp = ["trialwise"]
definition_video = ["trialwise"]

[experiment]
optional = ["compute_first_two_feature_series_only", "fps", "frame", "inspect_arg", "inspect_image_path", "manual_inspect_image", "manual_trial_ids", "manual_video", "meters_per_pixel", "minimum_frame_length", "recording_resolution", "skip_habituation", "stage", "trial_init_error_out_dir"]

[experiment.defined]

[trial]
[trial.common]
optional = ["animal_profile", "center_rectangle_dimensions_to_spatial_resolution_ratio", "coordinate_timestamp_index", "crop_from_end", "crop_time_seconds", "fps", "frame", "inspect_arg", "inspect_image_path", "length_meters_of_meters_per_pixel_source", "manual_center_pixels", "manual_center_rectangle_dimensions_meters", "manual_enclosure", "manual_inspect_image", "manual_perimeter_to_derive_meters_per_pixel", "manual_reader_kwargs", "manual_video", "meters_per_pixel", "meters_per_pixel_from_perimeter", "meters_per_pixel_from_perimeter_source", "minimum_frame_length", "physical_object_inspect", "reader_class_label", "recording_resolution", "rectangle_2d_bin", "trial_start_perimeter"]

[trial.common.defined]
crop_from_end = false

[trial.ObjectsInUpdatingLocationsTestTrial]
class_name = "ObjectsInUpdatingLocationsTestTrial"
optional = ["animal_profile", "center_rectangle_dimensions_to_spatial_resolution_ratio", "coordinate_timestamp_index", "crop_from_end", "crop_time_seconds", "fps", "frame", "inspect_arg", "inspect_image_path", "length_meters_of_meters_per_pixel_source", "manual_center_pixels", "manual_center_rectangle_dimensions_meters", "manual_enclosure", "manual_inspect_image", "manual_perimeter_to_derive_meters_per_pixel", "manual_reader_kwargs", "manual_video", "meters_per_pixel", "meters_per_pixel_from_perimeter", "meters_per_pixel_from_perimeter_source", "minimum_frame_length", "physical_object_inspect", "reader_class_label", "recording_resolution", "rectangle_2d_bin", "trial_start_perimeter"]

[trial.ObjectsInUpdatingLocationsTestTrial.defined]
crop_time_seconds = 300

[trial.ObjectsInUpdatingLocationsUpdateTrial]
class_name = "ObjectsInUpdatingLocationsUpdateTrial"
optional = ["animal_profile", "center_rectangle_dimensions_to_spatial_resolution_ratio", "coordinate_timestamp_index", "crop_from_end", "crop_time_seconds", "fps", "frame", "inspect_arg", "inspect_image_path", "length_meters_of_meters_per_pixel_source", "manual_center_pixels", "manual_center_rectangle_dimensions_meters", "manual_enclosure", "manual_inspect_image", "manual_perimeter_to_derive_meters_per_pixel", "manual_reader_kwargs", "manual_video", "meters_per_pixel", "meters_per_pixel_from_perimeter", "meters_per_pixel_from_perimeter_source", "minimum_frame_length", "physical_object_inspect", "reader_class_label", "recording_resolution", "rectangle_2d_bin", "trial_start_perimeter"]

[trial.ObjectsInUpdatingLocationsUpdateTrial.defined]
crop_time_seconds = 300

[trial.ObjectsInUpdatingLocationsTrainingTrial]
class_name = "ObjectsInUpdatingLocationsTrainingTrial"
optional = ["animal_profile", "center_rectangle_dimensions_to_spatial_resolution_ratio", "coordinate_timestamp_index", "crop_from_end", "crop_time_seconds", "fps", "frame", "inspect_arg", "inspect_image_path", "length_meters_of_meters_per_pixel_source", "manual_center_pixels", "manual_center_rectangle_dimensions_meters", "manual_enclosure", "manual_inspect_image", "manual_perimeter_to_derive_meters_per_pixel", "manual_reader_kwargs", "manual_video", "meters_per_pixel", "meters_per_pixel_from_perimeter", "meters_per_pixel_from_perimeter_source", "minimum_frame_length", "physical_object_inspect", "reader_class_label", "recording_resolution", "rectangle_2d_bin", "trial_start_perimeter"]

[trial.ObjectsInUpdatingLocationsTrainingTrial.defined]
crop_time_seconds = 900

[enclosure.RectanglePerimeter]
class_name = "RectanglePerimeter"
optional = ["derive_meters_per_pixel", "derived_meters_per_pixel_source", "derived_meters_per_pixel_source_metric_length", "fps", "frame", "impenetrable", "inspect_arg", "inspect_image_path", "manual_inspect_image", "manual_video", "meters_per_pixel", "minimum_frame_length", "moving_field_name", "recording_resolution"]

[enclosure.RectanglePerimeter.defined]

[perimeter]
[perimeter.common]
optional = ["derive_meters_per_pixel", "derived_meters_per_pixel_source", "derived_meters_per_pixel_source_metric_length", "fps", "frame", "impenetrable", "inspect_arg", "inspect_image_path", "manual_inspect_image", "manual_video", "meters_per_pixel", "minimum_frame_length", "moving_field_name", "recording_resolution"]

[perimeter.common.defined]
impenetrable = true

[perimeter.object_1]
class_name = "BaseSinglePerimeter"
optional = ["derive_meters_per_pixel", "derived_meters_per_pixel_source", "derived_meters_per_pixel_source_metric_length", "fps", "frame", "impenetrable", "inspect_arg", "inspect_image_path", "manual_inspect_image", "manual_video", "meters_per_pixel", "minimum_frame_length", "moving_field_name", "recording_resolution"]

[perimeter.object_1.defined]

[perimeter.object_2]
class_name = "BaseSinglePerimeter"
optional = ["derive_meters_per_pixel", "derived_meters_per_pixel_source", "derived_meters_per_pixel_source_metric_length", "fps", "frame", "impenetrable", "inspect_arg", "inspect_image_path", "manual_inspect_image", "manual_video", "meters_per_pixel", "minimum_frame_length", "moving_field_name", "recording_resolution"]

[perimeter.object_2.defined]

[perimeter.object_4]
class_name = "BaseSinglePerimeter"
optional = ["derive_meters_per_pixel", "derived_meters_per_pixel_source", "derived_meters_per_pixel_source_metric_length", "fps", "frame", "impenetrable", "inspect_arg", "inspect_image_path", "manual_inspect_image", "manual_video", "meters_per_pixel", "minimum_frame_length", "moving_field_name", "recording_resolution"]

[perimeter.object_4.defined]

[perimeter.object_3]
class_name = "BaseSinglePerimeter"
optional = ["derive_meters_per_pixel", "derived_meters_per_pixel_source", "derived_meters_per_pixel_source_metric_length", "fps", "frame", "impenetrable", "inspect_arg", "inspect_image_path", "manual_inspect_image", "manual_video", "meters_per_pixel", "minimum_frame_length", "moving_field_name", "recording_resolution"]

[perimeter.object_3.defined]

[perimeter_plugin.PluginSinglePerimeter]
class_name = "PluginSinglePerimeter"
required = ["data_path"]
optional = ["label_prefix", "label_suffix", "manual_reference", "manual_shape", "manual_trial_argument_key", "plural_entries"]

[perimeter_plugin.PluginSinglePerimeter.defined]
label_prefix = "object"

[runtime_settings]
optional = ["debug", "disable_numba", "disable_process_pooling", "ignore_pre_existing_inspection_directory", "matplotlib_invert_y_axis", "matplotlib_scatter_alpha", "maximum_seconds_distraction", "minimum_seconds_tolerance", "only_physical_cores"]

[runtime_settings.defined]

[reader]
required = ["object_tracking_label_for_kinematics"]
optional = ["cache_meters_augmented", "crop_from_end", "crop_time_seconds", "df_is_timestamped", "df_read_kwargs", "export_timestamp_data_as_parquet", "fps", "frame", "future_scaling", "invert_y_axis", "manual_video", "meters_per_pixel", "midpoint_groups", "min_likelihood", "minimum_frame_length", "model", "model_displacement_by_std", "model_kwargs", "model_method", "recording_resolution", "required_tail_likelihood", "x_axis_crop_end_point", "y_axis_crop_end_point"]

[reader.defined]
midpoint_groups = { center_eye = ["left_ear", "right_ear"] }
object_tracking_label_for_kinematics = "center_eye"

[field]
animal_profile = "string(default: rodent)"
cache_meters_augmented = "boolean(default: True)"
center_rectangle_dimensions_to_spatial_resolution_ratio = "number"
compute_first_two_feature_series_only = "boolean(default: False)"
coordinate_timestamp_index = "np.ndarray"
crop_from_end = "boolean(default: False)"
crop_time_seconds = "number(default: 0.0)"
data_path = "string"
dataset_directory = "string"
debug = "boolean(default: False)"
definition_center = "array"
definition_change_reference = "array"
definition_enclosure = "array"
definition_frame = "array"
definition_meters_per_pixel = "array"
definition_radial = "array"
definition_single_perimeter = "array"
definition_timestamp = "array"
definition_video = "array"
deprecated_project_settings_file_name = "boolean(default: False)"
derive_meters_per_pixel = "boolean(default: False)"
derived_meters_per_pixel_source = "string"
derived_meters_per_pixel_source_metric_length = "number"
df_is_timestamped = "boolean(default: False)"
df_read_kwargs = "object"
disable_numba = "boolean(default: False)"
disable_process_pooling = "boolean(default: False)"
export_timestamp_data_as_parquet = "boolean(default: False)"
first_stage_is_habituation = "boolean(default: False)"
fps = "number"
frame = "Any[string, array]"
future_scaling = "boolean"
ignore_pre_existing_inspection_directory = "boolean(default: False)"
impenetrable = "boolean(default: False)"
ingress_defined_perimeters = "object(default: {})"
inspect_arg = "Any[string, boolean](default: False)"
inspect_image_path = "string"
invert_y_axis = "boolean(default: False)"
label_prefix = "string"
label_suffix = "string"
length_meters_of_meters_per_pixel_source = "number"
manual_center_pixels = "np.ndarray[name='manual_center_pixels_0' type=int required=True]"
manual_center_rectangle_dimensions_meters = "np.ndarray[name='manual_center_rectangle_dimensions_meters_0' type=float required=True]"
manual_enclosure = "All[[{'$ref': '#/definitions/BasePerimeter'}]]"
manual_inspect_image = "np.ndarray[name='manual_inspect_image_0' type=int required=True]"
manual_perimeter_to_derive_meters_per_pixel = "string"
manual_reader_kwargs = "object"
manual_reference = "np.ndarray[name='manual_reference_0' type=float required=True]"
manual_shape = "string"
manual_trial_argument_key = "string"
manual_trial_ids = "array"
manual_video = "All[[{'$ref': '#/definitions/VideoMetadata'}]]"
matplotlib_invert_y_axis = "boolean(default: False)"
matplotlib_scatter_alpha = "number(default: 0.6)"
maximum_seconds_distraction = "number(default: 0.6666666666666666)"
metadata_trial_ids_are_higher_level = "boolean(default: False)"
meters_per_pixel = "Any[number, array]"
meters_per_pixel_from_perimeter = "boolean(default: False)"
meters_per_pixel_from_perimeter_source = "string"
midpoint_groups = "object"
min_likelihood = "number(default: 0.8)"
minimum_frame_length = "integer(default: 600)"
minimum_seconds_tolerance = "number(default: 0.2)"
model = "boolean(default: True)"
model_displacement_by_std = "number(default: 2.0)"
model_kwargs = "object"
model_method = "string(default: arima)"
moving_field_name = "string"
object_tracking_label_for_kinematics = "string"
only_physical_cores = "boolean(default: False)"
physical_object_inspect = "boolean(default: False)"
plural_entries = "boolean(default: True)"
project_kit_config = "object"
reader_class_label = "string(default: DeepLabCutReader)"
recording_resolution = "np.ndarray[name='recording_resolution_0' type=int required=True]"
rectangle_2d_bin = "array(default: (2, 2))"
required_tail_likelihood = "number(default: 0.8)"
skip_habituation = "boolean(default: False)"
stage = "string"
trial_init_error_out_dir = "string"
trial_sequence_loops = "integer(default: 1)"
trial_start_perimeter = "string"
x_axis_crop_end_point = "number(default: 0.0)"
y_axis_crop_end_point = "number(default: 0.0)"
