Python_version = "3.10.10"
schema_snapshot = ["manual", "perimeter", "experiment", "ingress", "enclosure", "plugin", "trial", "runtime_settings", "reader", "field"]

[ProjectKit]
format = ".toml"
version = "0.2.2"

[new_kwargs]
