ingress_method: phase
first_stage_is_habituation: true
manual_dataset_directory: /home/can/Downloads/Compressed/nort/
ingress:
  meters_per_pixel_definition_strategy: global
  perimeter_definition_strategy: metadata
  radial_definition_strategy: null
  change_reference_definition_strategy: metadata
  video_definition_strategy: trial-wise
  center_definition_strategy: null
  frame_upscale_multiplier: 2.0
  profile_runtime: true
perimeter:
  label_prefix: null
  label_suffix: null
  perimeter_names_in_metadata: false
  radial_arm_rectangle_diagonal: null
  fields:
    defined: {}
    optional:
      impenetrable: boolean -> False
      inspect_arg: '[{''type'': ''string'', ''format'': ''directory-path''}, {''type'':
        ''boolean''}] -> False'
      inspect_image_path: string
      manual_fps: number
      manual_frame: '[{''type'': ''np.ndarray''}, {''type'': ''string'', ''format'':
        ''file-path''}]'
      manual_inspect_image: np.ndarray
      manual_recording_resolution: np.ndarray[name='manual_recording_resolution_0'
        type=short required=True]
      manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
      meters_per_pixel: np.ndarray[name='meters_per_pixel_0' type=dobble required=True]
      video_path: string
reader_kwargs:
  defined:
    midpoint_groups:
      center_eye:
      - left_ear
      - right_ear
      torso:
      - center_eye
      - tail
  optional:
    crop_from_end: boolean -> False
    crop_time_seconds: number -> 0.0
    future_scaling: boolean
    manual_fps: number
    manual_frame: '[{''type'': ''string'', ''format'': ''file-path''}, {''type'':
      ''np.ndarray''}]'
    manual_recording_resolution: np.ndarray[name='manual_recording_resolution_0' type=short
      required=True]
    manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
    meters_per_pixel: np.ndarray[name='meters_per_pixel_0' type=dobble required=True]
    midpoint_groups: object
    min_likelihood: number -> 0.8
    reverse_y_axis: boolean -> True
    video_path: string
    x_axis_crop_end_point: number -> 0.0
    y_axis_crop_end_point: number -> 0.0
trial:
  common:
    defined:
      gaze_start_point_label: center_eye
      gaze_travel_direction_point_label: nose
      object_tracking_label_for_kinematics: center_eye
      outside_perimeter_point_label: torso
      perimeter_border_normal_meters: 0.06
      outdated:
        familiar: null
      maximum_radians_inter_gaze_perimeter: 1.5707963267948966
    required:
      gaze_start_point_label: string
      gaze_travel_direction_point_label: string
      object_tracking_label_for_kinematics: string
      outside_perimeter_point_label: string
      perimeter_border_normal_meters: number
    optional:
      center_rectangle_dimensions_to_spatial_resolution_ratio: number
      crop_from_end: boolean -> True
      crop_time_seconds: number -> 0.0
      data_format_label: string -> deeplabcut
      inspect_arg: '[{''type'': ''string'', ''format'': ''path''}, {''type'': ''boolean''}]
        -> False'
      inspect_image_path: string
      inspect_quadrants: boolean -> False
      manual_center_pixels: np.ndarray[name='manual_center_pixels_0' type=short required=True]
      manual_center_rectangle_dimensions_meters: np.ndarray[name='manual_center_rectangle_dimensions_meters_0'
        type=dobble required=True]
      manual_fps: number
      manual_frame: '[{''type'': ''string'', ''format'': ''file-path''}, {''type'':
        ''np.ndarray''}]'
      manual_inspect_image: np.ndarray
      manual_recording_resolution: np.ndarray[name='manual_recording_resolution_0'
        type=short required=True]
      manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
      maximum_radians_inter_gaze_perimeter: number -> 0.7853981633974483
      maximum_seconds_distraction: number -> 0.6666666666666666
      meters_per_pixel: np.ndarray[name='meters_per_pixel_0' type=dobble required=True]
      minimum_seconds_attention: number -> 0.3333333333333333
      physical_object_inspect: boolean -> False
      rectangle_2d_bin: array -> (2, 2)
      rigid_nodes_freezing: array
      trial_start_perimeter: string
      video_path: string
  specific: {}
experiment:
  defined:
    compute_only_one_df_row: true
  optional:
    compute_only_one_df_row: boolean -> False
    data_format_label: string -> deeplabcut
    inspect_arg: '[{''type'': ''string'', ''format'': ''path''}, {''type'': ''boolean''}]
      -> False'
    inspect_image_path: string
    manual_fps: number
    manual_frame: '[{''type'': ''string'', ''format'': ''file-path''}, {''type'':
      ''np.ndarray''}]'
    manual_inspect_image: np.ndarray
    manual_recording_resolution: np.ndarray[name='manual_recording_resolution_0' type=short
      required=True]
    manual_trial_ids: array
    manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
    meters_per_pixel: np.ndarray[name='meters_per_pixel_0' type=dobble required=True]
    stage: string
    video_path: string
immutable:
  metadata_filename: metadata.xlsx
  kinematic_data_file_extension: .parquet
  experiment_class: nort
  stage_index_to_trial_class_name:
    0: NortTrainingTrial
    1: NortNoveltyTrial
