[immutable]
metadata_filename = "metadata.xlsx"
experiment_class = "ObjectsInUpdatingLocationsExperiment"
trial_sequence = ["ObjectsInUpdatingLocationsTrainingTrial", "ObjectsInUpdatingLocationsUpdateTrial", "ObjectsInUpdatingLocationsTestTrial"]

[developer]
activate_debugging = false

[developer.settings]
disable_numba = false
disable_process_pooling = false
only_physical_cores = false

[ingress]
method = "animal"
animal_profile = "rodent"
first_stage_is_habituation = true
metadata_trial_ids_are_higher_level = false
trial_sequence_loops = ""
framewise_coordinates_file_suffix = ".h5"
dataset_directory = "/data/behaviour_dataset/dejana/OUL_120123_organized_mextracted"
profile_runtime = true

[definition_strategies]
meters_per_pixel = "metadata"
perimeter = "trial-wise"
enclosure = "metadata"
radial = ""
change_reference = ""
frame = ""
video = "trial-wise"
timestamp = "trial-wise"
center = "metadata"

[manual_reader_kwargs]
[manual_reader_kwargs.defined]
object_tracking_label_for_kinematics = "center_eye"

[manual_reader_kwargs.defined.midpoint_groups]
center_eye = ["left_ear", "right_ear"]

[manual_reader_kwargs.required]
object_tracking_label_for_kinematics = "string"

[manual_reader_kwargs.optional]
cache_meters_augmented = "boolean -> True"
crop_from_end = "boolean -> False"
crop_time_seconds = "number -> 0.0"
df_is_timestamped = "boolean -> False"
df_read_kwargs = "object"
export_timestamp_data_as_parquet = "boolean -> False"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
future_scaling = "boolean"
invert_y_axis = "boolean -> False"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
midpoint_groups = "object"
min_likelihood = "number -> 0.8"
minimum_frame_length = "integer -> 600"
model = "boolean -> True"
model_displacement_by_std = "number -> 2.0"
model_kwargs = "object"
model_method = "string -> arima"
recording_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"
required_tail_likelihood = "number -> 0.8"
x_axis_crop_end_point = "number -> 0.0"
y_axis_crop_end_point = "number -> 0.0"

[trial]
[trial.common]
[trial.common.defined]
crop_from_end = false

[trial.common.optional]
center_rectangle_dimensions_to_spatial_resolution_ratio = "number"
coordinate_timestamp_index = "np.ndarray"
crop_from_end = "boolean -> False"
crop_time_seconds = "number -> 0.0"
enclosure = "[{'$ref': '#/definitions/BasePerimeter'}]"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
inspect_arg = "[{'type': 'string', 'format': 'path'}, {'type': 'boolean'}]"
inspect_image_path = "string"
length_meters_of_meters_per_pixel_source = "number"
manual_center_pixels = "np.ndarray[name='manual_center_pixels_0' type=short required=True]"
manual_center_rectangle_dimensions_meters = "np.ndarray[name='manual_center_rectangle_dimensions_meters_0' type=dobble required=True]"
manual_enclosure = "[{'$ref': '#/definitions/BasePerimeter'}]"
manual_inspect_image = "np.ndarray[name='manual_inspect_image_0' type=uint8 required=True]"
manual_perimeter_to_derive_meters_per_pixel = "string"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
meters_per_pixel_from_perimeter = "boolean -> False"
meters_per_pixel_from_perimeter_source = "string"
minimum_frame_length = "integer -> 600"
physical_object_inspect = "boolean -> False"
reader_class_label = "string -> DeepLabCutReader"
recording_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"
rectangle_2d_bin = "array -> (2, 2)"
rigid_nodes_freezing = "array"
trial_start_perimeter = "string"

[trial.specific]
[trial.specific.ObjectsInUpdatingLocationsTrainingTrial.defined]
crop_time_seconds = 900

[trial.specific.ObjectsInUpdatingLocationsUpdateTrial.defined]
crop_time_seconds = 300
crop_from_end = false

[trial.specific.ObjectsInUpdatingLocationsTestTrial.defined]
crop_time_seconds = 300

[experiment]
[experiment.defined]
fps = 30

[experiment.optional]
compute_first_two_feature_series_only = "boolean -> False"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
inspect_arg = "[{'type': 'string', 'format': 'path'}, {'type': 'boolean'}] -> False"
inspect_image_path = "string"
manual_inspect_image = "np.ndarray[name='manual_inspect_image_0' type=uint8 required=True]"
manual_trial_ids = "array"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
minimum_frame_length = "integer -> 600"
recording_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"
skip_habituation = "boolean -> False"
stage = "string"
trial_init_error_out_dir = "string"

[perimeter]
label_prefix = "object"
label_suffix = ""
perimeter_names_in_metadata = false
radial_arm_rectangle_diagonal = -1

[perimeter.common]
[perimeter.common.defined]
impenetrable = true

[perimeter.common.optional]
derive_meters_per_pixel = "boolean -> False"
derived_meters_per_pixel_source = "string"
derived_meters_per_pixel_source_metric_length = "number"
fps = "number"
frame = "[{'type': 'string', 'format': 'file-path'}, {'type': 'uint8'}]"
impenetrable = "boolean -> False"
inspect_arg = "[{'type': 'string', 'format': 'path'}, {'type': 'boolean'}] -> False"
inspect_image_path = "string"
manual_inspect_image = "np.ndarray[name='manual_inspect_image_0' type=uint8 required=True]"
manual_video = "[{'$ref': '#/definitions/VideoMetadata'}]"
meters_per_pixel = "[{'type': 'number'}, {'type': 'dobble'}]"
minimum_frame_length = "integer -> 600"
moving_field_name = "string"
recording_resolution = "np.ndarray[name='recording_resolution_0' type=short required=True]"

[perimeter.trial_perimeters]
