Python_version = "3.10.10"
schema_snapshot = ["manual", "perimeter", "runtime_settings", "perimeter_plugin", "ingress", "trial", "enclosure", "reader", "experiment", "field"]

[ProjectKit]
format = ".toml"
version = "0.2.2"

[new_kwargs]
