Python_version = "3.11.3"
schema_snapshot = ["manual", "trial", "ingress", "reader", "perimeter", "experiment", "runtime_settings", "field", "plugin"]

[ProjectKit]
format = ".toml"
version = "0.2.2"

[new_kwargs]
