[package]
name = "bikipy-feature"
description = "Heuristic algorithms and feature extraction for bikipy"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bikipy-core.workspace = true
bikipy-math.workspace = true
bikipy-perimeter.workspace = true
polars.workspace = true
serde.workspace = true
