ingress_method: phase
first_stage_is_habituation: false
manual_dataset_directory: /home/can/Downloads/Compressed/y_maze/
ingress:
  meters_per_pixel_definition_strategy: radial
  perimeter_definition_strategy: null
  radial_definition_strategy: metadata
  change_reference_definition_strategy: metadata
  video_definition_strategy: trial-wise
  center_definition_strategy: null
perimeter:
  label_prefix: null
  label_suffix: null
  perimeter_names_in_metadata: false
  radial_arm_rectangle_diagonal: 0.359026
  fields:
    defined: {}
    optional:
      impenetrable: boolean -> False
      inspect_arg: '[{''type'': ''string'', ''format'': ''directory-path''}, {''type'':
        ''boolean''}] -> False'
      inspect_image_path: string
      manual_fps: number
      manual_frame: '[{''type'': ''np.ndarray''}, {''type'': ''string'', ''format'':
        ''file-path''}]'
      manual_inspect_image: np.ndarray
      manual_recording_resolution: np.ndarray[name='manual_recording_resolution_0'
        type=short required=True]
      manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
      meters_per_pixel: np.ndarray[name='meters_per_pixel_0' type=dobble required=True]
      video_path: string
      outdated:
        group_label: string
        int_id: integer
        makesense_image_name: string
        reference_point_array: np.ndarray[name='reference_point_array_0' type=short
          required=True]
        reference_point_coco_path: string
        outdated:
          inspect: boolean -> False
          inspect_directory: string
    outdated:
      required:
        label: string
reader_kwargs:
  defined:
    x_axis_crop_end_point: 95.0
    y_axis_crop_end_point: 75.0
    midpoint_groups:
      center_eye:
      - left_ear
      - right_ear
      torso:
      - center_eye
      - base_tail
  optional:
    crop_from_end: boolean -> False
    crop_time_seconds: number -> 0.0
    future_scaling: boolean
    manual_fps: number
    manual_frame: '[{''type'': ''np.ndarray''}, {''type'': ''string'', ''format'':
      ''file-path''}]'
    manual_recording_resolution: np.ndarray[name='manual_recording_resolution_0' type=short
      required=True]
    manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
    meters_per_pixel: np.ndarray[name='meters_per_pixel_0' type=dobble required=True]
    midpoint_groups: object
    min_likelihood: number -> 0.8
    reverse_y_axis: boolean -> True
    video_path: string
    x_axis_crop_end_point: number -> 0.0
    y_axis_crop_end_point: number -> 0.0
trial:
  common:
    defined:
      object_labels_for_y_maze_confinement_tracking:
      - center_eye
      - torso
      - base_tail
      object_tracking_label_for_kinematics: torso
    required:
      object_labels_for_y_maze_confinement_tracking: array
      object_tracking_label_for_kinematics: string
    optional:
      crop_from_end: boolean -> True
      crop_time_seconds: number -> 0.0
      data_format_label: string -> deeplabcut
      inspect_arg: '[{''type'': ''string'', ''format'': ''directory-path''}, {''type'':
        ''boolean''}] -> False'
      inspect_image_path: string
      manual_center_pixels: np.ndarray[name='manual_center_pixels_0' type=short required=True]
      manual_fps: number
      manual_frame: '[{''type'': ''np.ndarray''}, {''type'': ''string'', ''format'':
        ''file-path''}]'
      manual_recording_resolution: np.ndarray[name='manual_recording_resolution_0'
        type=short required=True]
      manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
      meters_per_pixel: np.ndarray[name='meters_per_pixel_0' type=dobble required=True]
      minimum_seconds_for_entry: number -> 0.5
      rigid_nodes_freezing: array
      trial_start_perimeter: string
      video_path: string
  specific: {}
experiment:
  defined: {}
  optional:
    compute_only_one_df_row: boolean -> False
    data_format_label: string -> deeplabcut
    inspect_arg: '[{''type'': ''string'', ''format'': ''directory-path''}, {''type'':
      ''boolean''}] -> False'
    inspect_image_path: string
    manual_fps: number
    manual_frame: '[{''type'': ''np.ndarray''}, {''type'': ''string'', ''format'':
      ''file-path''}]'
    manual_recording_resolution: np.ndarray[name='manual_recording_resolution_0' type=short
      required=True]
    manual_trial_ids: array
    manual_video: '[{''$ref'': ''#/definitions/VideoMetadata''}]'
    meters_per_pixel: np.ndarray[name='meters_per_pixel_0' type=dobble required=True]
    stage: string
    video_path: string
immutable:
  metadata_filename: metadata.xlsx
  kinematic_data_file_extension: .parquet
  experiment_class: y_maze
  trial_classes:
  - YMazeTrial
